### ISSUE TITLE
Disable SDL2

### ISSUE THREAD

**Issue by Nikoru14** [alvaromunoz/chiaki-builds#3]
How do I disable SDL2 support? The issue is that I''m getting duplicate input because I'm using a Switch Pro Controller paired with a program called Betterjoy. this program creates a HID-compliant gamepad to remap Switch pro controller to xinput. Since this build has support for SDL2 im getting duplicate input whenever I press the face buttons. The face buttons on a Switch pro controller is the opposite layout on that of a xinput controller thus pressing A results in Chiaki reading both A from SDL2 (Switch pro) and B for (Xinput via better joy).

**Comment by perroboc** [comment]
This is a key part of Chiaki, I understand it can’t be disabled. Also, this is only a repo for custom builds, changes to the source code should go to the official Chiaki repo.
