### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by QwerkyPengwen** [alvaromunoz/chiaki-builds#5]
Hi, I posted to the reddit thread the other day in hopes you might see it not realizing the account was deleted lol.
So I am posting here in hopes I can get a message to you.

I am posting here just to say two things:

#1. Thank you very much for this build, because unlike the official build this has working hardware decoders (and more options as well).
I am able to use CUDA decoder option with H265 and the maximum bitrate of 99,999 (overkill, but did it just to test) without any issues with glitches and the video quality is near perfect (similar to the quality I get from Parsec), I do of course have to use the VC non QT build so I can delete the qtaudio_windows.dll to get audio where I want it, but also I can set the buffer to 1000 and it's pretty much instant audio/visual sync.
So again, thank you for your build.

#2. I am wondering if there are any plans to/if it is possible to get an updated build that uses the latest 2.2 build with the DualSense haptics and adaptive trigger support? Other than the lack of the newer DualSense features your build is in my opinion superior to the official build because it has working hardware decoders.

**Comment by perroboc** [comment]
A refresh of versions might be a good thing. I’ll look for some free time to do so.

**Comment by QwerkyPengwen** [comment]
> A refresh of versions might be a good thing. I’ll look for some free time to do so.

That sounds awesome :) thank you.
